events {}

http {
  client_header_buffer_size 64k;
  large_client_header_buffers 4 64k;

  server {
    listen 80;

    location /orthanc/ {
        rewrite ^/orthanc/(.*)$ /$1 break;
        proxy_pass http://orthanc:8042/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";

        proxy_buffering off;
        proxy_request_buffering off;
        chunked_transfer_encoding off;

        proxy_set_header Accept-Encoding "";
    }

    location /orthanc-adapter/ {
        rewrite ^/orthanc-adapter/(.*)$ /$1 break;
        proxy_pass http://orthanc-adapter:80/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Connection "";

        proxy_buffering off;
        proxy_request_buffering off;
        chunked_transfer_encoding off;

        proxy_set_header Accept-Encoding "";
    }

    location / {
      proxy_pass http://ohif;
    } 
  }
}